### ISSUE TITLE
Repair CSS in QA instance after accessibility improvements

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#563]
After accessibility improvement, several buttons and elements have lost their styling. Compare to staging and bring to similar visual style

**Comment by johnhbenetech** [comment]
Please bring the current dev branch (https://mathshare-qa.diagramcenter.org) visually closer to how the platform looked pre markup fixes (https://mathshare-staging.diagramcenter.org).

There are several obvious CSS related issues visible across the main user views.

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have pushed some fixes to the development branch, but the changes don't seem to reflect on https://mathshare-qa.diagramcenter.org
Not sure if the auto-deployment has kicked in after I pushed my commit

**Comment by johnhbenetech** [comment]
@rupeshparab The build actually failed. We'll have to think of a better way to get you these errors more real-time (if you aren't getting them in your local dev environment. Let me know if you feel these logs dont make sense and we should try something else:

WARNING in ./node_modules/reactour/dist/reactour.esm.js 137:18-35
"export 'createGlobalStyle' was not found in 'styled-components'
 @ ./src/components/Editor/components/ProblemHeader/index.js
 @ ./src/components/Editor/index.js
 @ ./src/components/index.js
 @ ./src/index.js

ERROR in ./src/components/Editor/stack.js
Module Error (from ./node_modules/eslint-loader/index.js):

/root/workspace/MathShare/src/components/Editor/stack.js
  2:1  error  Dependency cycle detected  import/no-cycle

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Editor/index.js 33:0-68 273:6-21 411:17-31 414:17-25
 @ ./src/components/index.js
 @ ./src/index.js

ERROR in ./src/components/Editor/stepsOperations.js
Module Error (from ./node_modules/eslint-loader/index.js):

/root/workspace/MathShare/src/components/Editor/stepsOperations.js
  2:1  error  Dependency cycle detected  import/no-cycle

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Editor/index.js 34:0-78 399:17-27 402:17-25 408:17-24 417:17-27
 @ ./src/components/index.js
 @ ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.38 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! MathShare@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the MathShare@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rupeshparab** [comment]
@johnhbenetech 
I had faced this issue while trying to setup the repo locally
To fix this issue, I had to upgrade the 'styled-components' package
I thought it might have been an environment issue, so I had not committed the package.json file
Will try to commit the package.json file and retry

Also, it would be great if I could get access to the deployment logs

**Comment by johnhbenetech** [comment]
latest build still failed

ERROR in ./src/components/Editor/stack.js
Module Error (from ./node_modules/eslint-loader/index.js):

/root/workspace/MathShare/src/components/Editor/stack.js
  2:1  error  Dependency cycle detected  import/no-cycle

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Editor/index.js 33:0-68 308:6-21 446:17-31 449:17-25
 @ ./src/components/index.js
 @ ./src/index.js

ERROR in ./src/components/Editor/stepsOperations.js
Module Error (from ./node_modules/eslint-loader/index.js):

/root/workspace/MathShare/src/components/Editor/stepsOperations.js
  2:1  error  Dependency cycle detected  import/no-cycle

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Editor/index.js 34:0-78 434:17-27 437:17-25 443:17-24 452:17-27
 @ ./src/components/index.js
 @ ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.38 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module

**Comment by johnhbenetech** [comment]
@rupeshparab ok, I am now having jenkins send an email (to your toptal address) whenever a build fails. It should have the build log attached as a .log file

**Comment by rupeshparab** [comment]
@johnhbenetech 
The fixes have been deployed in QA
https://mathshare-qa.diagramcenter.org/
